version: "3.8"

services:
    mysql:
        image: mysql:8.3.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: morgana
        ports:
            - "3306:3306"

    redis:
        image: redis:7.2.4
        restart: always
        ports:
            - "6379:6379"
